# Generated by Django 2.2.5 on 2019-09-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_uid', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('working', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_clock_register', models.DateTimeField(default=None)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Timeclocks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sent', models.IntegerField(max_length=11)),
                ('clocking_time', models.DateTimeField(default=None)),
                ('clock_status', models.IntegerField(max_length=1)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Employees')),
            ],
        ),
    ]
