# Generated by Django 2.2.5 on 2019-09-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190905_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='timeclocks',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
