# Generated by Django 2.2.5 on 2019-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20190905_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timeclocks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
