# Generated by Django 2.2.5 on 2019-09-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190905_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Timeclocks',
            new_name='Timeclock',
        ),
    ]
